addpath(genpath('utility'))
close all
datalayer=DataLayer;
%datalayer.update('ModelFitODE_UnregulatedReducedModel')
%datalayer.update('ModelFitODEUnregulatedReducedModel_Calibration')
%datalayer.update('AnalysisODEFrequencySeparation_ReducedModels')
%datalayer.update('AnalysisODEHysteresis_ReducedModelUnregulated')
%datalayer.update('AnalysisODEHysteresis_ReducedModelAutoregulated')
%datalayer.update('AnalysisODESSAFrequency_ReducedModel')
%datalayer.update('AnalysisODEFrequencyOmegaCrit_ReducedModel')
%datalayer.update('ControlInputs_ReducedModels')
%datalayer.update('AnalysisFSPReducedModelControlPairs')
%datalayer.update('AnalysisSSATwoCellSwapReducedModel')
%datalayer.update('AnalysisSSAFourCellSwapReducedModel')
%datalayer.update('AnalysisSSAFSPPredictiveModelControl')
%datalayer.update('CalibrationCurveUnregulatedFullReduced')
%datalayer.get('CalibrationCurveHysteresisCalibratedModel');
%datalayer.get('AnalysisODEFrequencySeparation_FullModels')
figlayer=FigureLayer;
fig02=figlayer.Figure2;
fig03=figlayer.Figure3;
fig04=figlayer.Figure4;
fig05=figlayer.Figure5;
fig06=figlayer.Figure6;
fig07=figlayer.Figure7;
fig08=figlayer.Figure8;
%fig09=figlayer.Figure9;
% 
print(fig02,'figures/print/ModelFits.png','-dpng','-r600')
print(fig03,'figures/print/HystresisFrequency.png','-dpng','-r600')
print(fig04,'figures/print/SSAODE.png','-dpng','-r600')
print(fig05,'figures/print/3by5ReducedModels.png','-dpng','-r600')
print(fig06,'figures/print/ControlTrajectory_TwoCell','-dpng','-r600')
print(fig07,'figures/print/ControlTrajectory_FourCell','-dpng','-r600')
print(fig08,'figures/print/ControlTrajectory_Predictive','-dpng','-r600')