addpath(genpath('utility'))
close all
datalayer=DataLayer
%datalayer.update('AnalysisODEFrequencySeparation_ReducedModels')
%datalayer.update('AnalysisODEHysteresis_ReducedModelUnregulated')
%datalayer.update('AnalysisODEHysteresis_ReducedModelAutoregulated')
datalayer.update('AnalysisODESSAFrequency_ReducedModel')
%datalayer.update('AnalysisFSPReducedModelControlPairs')
%datalayer.update('AnalysisSSATwoCellSwapReducedModel')
%datalayer.update('AnalysisSSAFourCellSwapReducedModel')
%datalayer.update('AnalysisSSAFSPPredictiveModelControl')
%datalayer.update('ModelFitODE_UnregulatedReducedModel')
figlayer=FigureLayer;
fig02=figlayer.Figure2;
fig03=figlayer.Figure3;
fig04=figlayer.Figure4;
fig05=figlayer.Figure5;
fig06=figlayer.Figure6;
fig07=figlayer.Figure7;
fig08=figlayer.Figure8;
fig09=figlayer.Figure9;
fig10=figlayer.Figure10;